/**
 * Curated Phosphor icons bundled into icons.generated.ts.
 * Entries are Phosphor names; append `:fill` for the filled weight.
 * After editing, run `npm run icons` and commit the generated file.
 */
export const ICON_LIST = [
  // navigation and shell
  'house',
  'squares-four',
  'book-open',
  'gear',
  'sun',
  'moon',
  'list',
  'sign-out',
  'sign-in',
  'user',
  'chat-circle',
  'bell',
  // actions
  'x',
  'plus',
  'minus',
  'trash',
  'pencil-simple',
  'check',
  'floppy-disk',
  'share-network',
  'dots-three',
  'magnifying-glass',
  'camera',
  'image',
  // direction
  'caret-left',
  'caret-right',
  'caret-down',
  'caret-up',
  'arrow-left',
  'arrow-right',
  // domain
  'calendar-blank',
  'basket',
  'fire',
  'barbell',
  'fork-knife',
  'notebook',
  'coins',
  'wallet',
  'users',
  'folder',
  'receipt',
  'bank',
  'chart-line-up',
  'arrows-left-right',
  'piggy-bank',
  'credit-card',
  'money',
  'trend-up',
  'trend-down',
  'repeat',
  'funnel-simple',
  'link',
  'lock',
  // status
  'warning',
  'warning-circle',
  'info',
  'check-circle',
  'x-circle',
  'star',
  'star:fill',
  // journal moods
  'smiley',
  'smiley-sad',
  'heart',
  'lightning',
  'cloud',
  // Jym and Culinara
  'copy',
  'dots-six-vertical',
  'download-simple',
  'drop-slash',
  'globe',
  'grains-slash',
  'leaf',
  'lock-simple',
  'plant',
  'play:fill',
  'prohibit',
  'pulse',
  'video-camera',
  'trophy',
] as const;
