#!/usr/bin/env node
/**
 * Generates src/app/shared/icons/icons.generated.ts from the curated list in
 * src/app/shared/icons/icon-list.ts, using the SVG sources shipped by
 * @phosphor-icons/core (dev dependency only; the output is committed).
 *
 * Each entry is a Phosphor icon name, optionally suffixed with `:fill`.
 * Unknown names fail the build so typos are caught here, not in the browser.
 *
 *   npm run icons
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from "node:path";
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const { icons } = require('@phosphor-icons/core');
const known = new Set(icons.map(i => i.name));
// The package's exports map hides package.json, so locate the assets from node_modules directly.
const pkgDir = fileURLToPath(new URL('../node_modules/@phosphor-icons/core', import.meta.url));

const listPath = fileURLToPath(new URL('../src/app/shared/icons/icon-list.ts', import.meta.url));
const outPath = fileURLToPath(new URL('../src/app/shared/icons/icons.generated.ts', import.meta.url));

const entries = [...readFileSync(listPath, 'utf8').matchAll(/'([a-z0-9-]+(?::[a-z]+)?)'/g)].map(m => m[1]);
if (!entries.length) {
  console.error('build-icons: no entries found in icon-list.ts');
  process.exit(1);
}

const out = {};
for (const entry of entries) {
  const [name, weight = 'regular'] = entry.split(':');
  if (!known.has(name)) {
    console.error(`build-icons: "${name}" is not a Phosphor icon name`);
    process.exit(1);
  }
  const file = join(pkgDir, 'assets', weight, weight === 'regular' ? `${name}.svg` : `${name}-${weight}.svg`);
  const svg = readFileSync(file, 'utf8');
  // Keep only the drawing; the component supplies the <svg> wrapper and fill.
  const paths = [...svg.matchAll(/<path\b[^>]*\/?>/g)]
    .map(m => m[0].replace(/\s(?:fill|stroke)="[^"]*"/g, ''));
  if (!paths.length) {
    console.error(`build-icons: no <path> found in ${file}`);
    process.exit(1);
  }
  out[entry] = paths.join('');
}

const lines = Object.entries(out).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`);
const ts = `// GENERATED by scripts/build-icons.mjs from icon-list.ts. Do not edit by hand.
// Source: @phosphor-icons/core (MIT). viewBox 0 0 256 256, fill="currentColor".
export const ICONS = {
${lines.join('\n')}
} as const;

export type IconName = keyof typeof ICONS;
`;
writeFileSync(outPath, ts);
console.log(`build-icons: wrote ${entries.length} icons to ${outPath}`);
